spring.application.name=Spring_web_1

spring.datasource.url=jdbc:h2:mem:spring_web
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.servlet.context-path=/api

#logging.level.org.example.spring_web_1.Controller=debug
#logging.level.org.example.spring_web_1.Services=trace

#logging.level.root=debug
# we can specify our own pattern as well
logging.pattern.console = %c :%p --> %m ::  %d  %n

#making all that into a file
logging.file.name=logger/log.txt
logging.pattern.file=[%d] : %c :%p --> %m ::  %d  %n
