spring.application.name=Oauth2

spring.security.oauth2.client.registration.google.client-id=8806705739
spring.security.oauth2.client.registration.google.client-secret=


# similar for github also


spring.security.oauth2.client.registration.github.client-id=

spring.security.oauth2.client.registration.github.client-secret=


