spring.application.name=Oauth2

spring.security.oauth2.client.registration.google.client-id=880670573910-j11mb0amj2jsdrcqc23013jov8bo872r.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=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


# similar for github also


spring.security.oauth2.client.registration.github.client-id=Ov23liaDvJlSB7IANgpo

spring.security.oauth2.client.registration.github.client-secret=fd29f62a39f9fa7cfd23cd5487ec6d12db9fbf0d


